suggested offer of help
fortran-lang/fpm-registry pull request #23
Opened 2020-10-03 02:13 UTC by urbanjost

Not sure if everyone is open to just suggesting someone open an issue and ask for help but throwing it out there
for consideration.

2020-10-03 02:37 UTC, certik requested changes
I think that's a good idea. I left some comments.

2020-10-03 02:37 UTC, certik commented on README.md
> +[pull request](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
```suggestion
Please submit a Pull Request ([PR](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github))
```

2020-10-03 02:37 UTC, certik commented on README.md
> +**python** are putting you off from registering your package open an
```suggestion
**python** are putting you off from registering your package, please open an
```

2020-10-03 02:37 UTC, certik commented on README.md
> +far as you can and identify where you got stuck.
```suggestion
far as you can and identify where you got stuck. We will try to help.
```

2020-10-03 02:37 UTC, certik commented on README.md
> +## Are you kidding?
```suggestion
## How to request help
```

2020-10-03 06:01 UTC, urbanjost commented
Thanks.  Basically the request is that i"f you have a Fortran project in a git(1) repository you would like to share and have converted to an fpm(1) package please submit its' name for review".  There are quite a few steps being required 
to do that that I believe are off-putting for a good number of Fortran programmers. Seeing how many people ask for help might prove me wrong, but I am glad so see support for offering the time to help people over that threshold.

2020-10-03 13:45 UTC, LKedward approved these changes
Thanks @urbanjost, it's good to remove as many barriers as possible to new contributors.

2020-10-03 13:45 UTC, LKedward commented on README.md
> +far as you can and identify where you got stuck. We will try to help.
```suggestion
If you have a great Fortran package that you are interested
in registering as an **fpm** package but terms like **fpm**, **PR**, **toml**, and
**python** are putting you off, then please open an
[issue](https://github.com/fortran-lang/fpm-registry/issues) at the
**fpm Registry** site listing your Repository and let us know how we can help. Get as
far as you can and identify where you got stuck. We are always happy to help.
```

This is a *very* long multi-clause sentence; I have removed some redundancy and simplified.

2020-10-03 13:45 UTC, LKedward commented on README.md
> +in alphabetical order. Explicitly list each version using the
```suggestion
in alphabetical order. It is recommended that you explicitly list each version using the 
```

2020-10-03 13:45 UTC, LKedward commented on README.md
> +keyword, otherwise the master branch will be used. An example:
```suggestion
keyword, otherwise the tip of the master branch will be used. An example:
```

2020-10-03 14:25 UTC, certik commented
The way it will work is that right now we are happy to invest our time to help anyone who asks. As we get a bigger community, there will be more people to help, so it will scale. Just like in other communities, you just ask for help and somebody will help.

Why don't we also point them to our Discourse forum?

On Sat, Oct 3, 2020, at 12:02 AM, urbanjost wrote:
> 
> 
> Thanks. Basically the request is that i"f you have a Fortran project in 
> a git(1) repository you would like to share and have converted to an 
> fpm(1) package please submit its' name for review". There are quite a 
> few steps being required
> to do that that I believe are off-putting for a good number of Fortran 
> programmers. Seeing how many people ask for help might prove me wrong, 
> but I am glad so see support for offering the time to help people over 
> that threshold.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/fortran-lang/fpm-registry/pull/23#issuecomment-703052793>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAFAWGGRPDZRJM7MFKMKLLSI246FANCNFSM4SCK6F4Q>.
>

2020-10-03 14:29 UTC, awvwgk commented on README.md
> -```
This line was probably deleted by accident

2020-10-03 14:32 UTC, urbanjost commented
I tend to do that on a draft and then catch it. I remember Miss Dore (my English teacher) reminding me there is a difference between a paragraph and a sentence.  I tend to backslide when I'm in a hurry, I'm afraid.

2020-10-04 00:51 UTC, certik approved these changes
This looks good to me now. Thanks!

2020-10-04 01:16 UTC, milancurcic commented on registry.toml
>  "latest" = {git="https://github.com/urbanjost/M_strings"}
Alphabetical order:

```suggestion
[M_strings]
￼"latest" = {git="https://github.com/urbanjost/M_strings"}

[M_system]
￼"latest" = {git="https://github.com/urbanjost/M_system"}￼
```

2020-10-04 01:17 UTC, milancurcic approved these changes
Looks good. In the future, let's handle package submissions to the registry in a dedicated PR.

2020-10-05 15:22 UTC, merged